### ISSUE TITLE
Support reload for i18n dir

### ISSUE THREAD

**Issue by johnnyshields** [middleman/middleman-livereload#82] opened 2015-11-27 06:58 UTC
It seems that LiveReload handles changes within the source dir well. However, it does automatically reload for your i18n_dir (locale files). This would be a big help.

**Comment by tdreyno** [comment] 2015-11-27 23:27
Makes sense

**Comment by komor72** [comment] 2020-05-09 16:40
@tdreyno, I know this repo still has no maintainer (?), but this feature (live-reloading of `/locales/*.yml`) works OK since long. I use it daily in my Middleman projects. Used it even in old 3.4.1. I’ve just checked now and confirmed it really works in old v3.4.1-project. 

I'm pretty sure  you can close this issue. I know, there’s no test…

**Comment by tdreyno** [comment] 2020-05-10 00:39
Appreciate this @komor72

**Closed by tdreyno** 2020-05-10 00:39 UTC
